spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: 'jdbc:mariadb://49.247.147.147:3306/lullaby'
    hikari:
      username: 'lullaby'
      password: 'lullaby!@#'

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500