spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: {{url}}
    hikari:
      username: {{username}}
      password: {{password}}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500